# =============================================================================
# PALABRAS CLAVE
# =============================================================================
# El sistema solo enviará un aviso si el TÍTULO o el ÁREA de la convocatoria
# contiene alguna de estas palabras o frases (sin distinguir mayúsculas,
# minúsculas ni acentos).
# =============================================================================

palabras_clave:
  - "Matemáticas"
  - "Didáctica de la Matemática"
  - "Didáctica de las Matemáticas"
  - "Educación Matemática"
  - "Mathematics Education"
  - "Maestro"
  - "Educación Primaria"
  - "Facultad de Educación"
  - "STEM"
  - "Innovación Educativa"
  - "Didáctica de la Expresión Musical"
  - "Expresión Musical, Plástica y Corporal"
  - "DID.EXPRESIÓN MUSICAL"
  - "Departamento de Didáctica de las Ciencias Experimentales, Sociales y de la Matemática"
  - "DEPARTAMENTO: DID.EXPRESIÓN MUSICAL, PLAST.Y CORPORAL"
  - "Departamento de Didáctica de la Expresión Musical, Plástica y Corporal"
